# Generated by Django 4.1.2 on 2022-10-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('senha', models.CharField(max_length=6)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField(null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField(null=True)),
                ('telefone', models.CharField(max_length=9)),
                ('senha', models.CharField(max_length=6)),
                ('endereco', models.CharField(max_length=256, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
