# Generated by Django 4.1.2 on 2022-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('senha', models.CharField(max_length=6)),
                ('cpf', models.CharField(max_length=11)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
