# Generated by Django 4.1.2 on 2022-10-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_nome'),
    ]

    operations = [
    ]
