# Generated by Django 4.1.2 on 2022-10-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_data_nascimento'),
        ('usuario', '0005_usuario_usuario'),
    ]

    operations = [
    ]
