# Generated by Django 4.1.2 on 2022-10-28 02:31

from django.db import migrations, models
import validation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(unique=True, validators=[validation.validators.valida_cpf]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=8, unique=True, validators=[validation.validators.valida_senha]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[validation.validators.valida_telefone]),
        ),
    ]
