# Generated by Django 4.1.2 on 2022-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_cpf_alter_usuario_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
